#!/usr/bin/env python3
"""Build the standalone calculator site from the wiki sources.

Copies wiki/personal-common.js (the exact script the wiki runs) to calc.js,
and pulls the calculator sections out of wiki/Common.css into calc.css, so
the site and the wiki can never drift apart. Re-run after changing either.

    python3 build.py        # writes calc.js and calc.css next to this file
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
WIKI = os.path.join(HERE, '..', 'wiki')

css = open(os.path.join(WIKI, 'Common.css')).read()

# Top-level sections start with a "/* ===..." banner whose first text line
# names them. Keep the calculator ones, drop the rest (brainrot page layout,
# home page, Updates chips, navbox, Fandom gallery helpers).
WANTED = ('Value calculator', 'Trade calculator', 'My collection')
parts = re.split(r'(?m)^(?=/\* =+\s*$)', css)
kept = []
for part in parts:
    m = re.match(r'/\* =+\s*\n\s*(.+)', part)
    if m and m.group(1).strip().startswith(WANTED):
        kept.append(part.rstrip() + '\n')
missing = [w for w in WANTED if not any(re.match(r'/\* =+\s*\n\s*' + re.escape(w), k) for k in kept)]
if missing:
    raise SystemExit('Common.css sections not found: ' + ', '.join(missing))

with open(os.path.join(HERE, 'calc.css'), 'w') as f:
    f.write('/* Generated by build.py from wiki/Common.css. Do not edit. */\n\n')
    f.write('\n'.join(kept))

js = open(os.path.join(WIKI, 'personal-common.js')).read()
with open(os.path.join(HERE, 'calc.js'), 'w') as f:
    f.write('/* Generated by build.py from wiki/personal-common.js (the script the wiki runs). Do not edit. */\n')
    f.write(js)

# Stamp a content hash onto the links so browsers and GitHub's cache fetch
# the new files after every update instead of serving yesterday's.
import hashlib
ver = hashlib.sha256((js + '\n'.join(kept)).encode()).hexdigest()[:10]
for name, pat, rep in (
        ('app.js', r"s\.src = 'calc\.js(\?v=[0-9a-f]+)?'", "s.src = 'calc.js?v=%s'" % ver),
        ('index.html', r'href="calc\.css(\?v=[0-9a-f]+)?"', 'href="calc.css?v=%s"' % ver)):
    path = os.path.join(HERE, name)
    text = open(path).read()
    new_text, n = re.subn(pat, rep, text)
    if n != 1:
        raise SystemExit('could not stamp the version into ' + name)
    open(path, 'w').write(new_text)

print('wrote calc.css (%d sections) and calc.js (%d bytes), version %s' % (len(kept), len(js), ver))
