/* Generated by build.py from sw.template.js. Do not edit sw.js by hand. */
// Keeps the calculator page itself working without a signal. The figures
// come from the wiki; app.js keeps the last ones it got for offline use.
'use strict';
var CACHE = 'ffb-calc-ab7f44ee3c';
var SHELL = ["./", "index.html", "app.js?v=fbef25915c", "calc.js?v=afab7004d5", "calc.css?v=afab7004d5", "site.css?v=f764c63e31", "manifest.webmanifest", "icon-180.png", "icon-192.png", "icon-512.png"];

self.addEventListener( 'install', function ( e ) {
	e.waitUntil( caches.open( CACHE ).then( function ( c ) {
		return c.addAll( SHELL );
	} ).then( function () {
		return self.skipWaiting();
	} ) );
} );

self.addEventListener( 'activate', function ( e ) {
	e.waitUntil( caches.keys().then( function ( keys ) {
		return Promise.all( keys.filter( function ( k ) {
			return k.indexOf( 'ffb-calc-' ) === 0 && k !== CACHE;
		} ).map( function ( k ) {
			return caches.delete( k );
		} ) );
	} ).then( function () {
		return self.clients.claim();
	} ) );
} );

self.addEventListener( 'fetch', function ( e ) {
	var req = e.request;
	var url = new URL( req.url );
	// only this site's own files; the wiki's API goes straight to the network
	if ( req.method !== 'GET' || url.origin !== self.location.origin ) {
		return;
	}
	if ( req.mode === 'navigate' ) {
		// the page: fresh when online, the saved copy when not
		e.respondWith( fetch( req ).then( function ( res ) {
			var copy = res.clone();
			caches.open( CACHE ).then( function ( c ) {
				c.put( 'index.html', copy );
			} );
			return res;
		} ).catch( function () {
			return caches.match( 'index.html' );
		} ) );
		return;
	}
	// versioned files never change: the saved copy first
	e.respondWith( caches.match( req ).then( function ( hit ) {
		return hit || fetch( req );
	} ) );
} );
